--- #YAML:1.0
name: DBD-ODBC
abstract: ODBC DBD for Perl DBI
version: 1.17
version_from: ODBC.pm
author:
  - Tim Bunce
  - Jeff Urlwin
  - Martin J. Evans <mjevans@cpan.org>
license: perl
distribution_type: module
requires:
    DBI: 1.21
    perl: 5.006
#
# Added build_requires/configure_requires DBI as DBD::ODBC needs DBI::DBD to
# get postamble etc
#
build_requires:
  DBI: 1.21
configure_requires:
  DBI: 1.21
dynamic_config: 1
resources:
  license: http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DBD-ODBC
  MailingList: http://dbi.perl.org/
installdirs:  site
keywords:
  - ODBC
  - DBD
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Martin J. Evans