--- #YAML:1.0
name: DBD-ODBC
abstract: ODBC DBD for Perl DBI
version: 1.42_3
version_from: ODBC.pm
author:
  - Martin J. Evans <mjevans@cpan.org>
  - Tim Bunce
  - Jeff Urlwin
license: perl
distribution_type: module
dynamic_config : 1
requires:
    DBI: 1.609
    perl: 5.008
    Test::Simple: 0.90
#
# Added build_requires/configure_requires DBI as DBD::ODBC needs DBI::DBD to
# get postamble etc
#
build_requires:
  DBI: 1.21
  ExtUtils::MakeMaker: 0
configure_requires:
  DBI: 1.21
  ExtUtils::MakeMaker: 0
dynamic_config: 1
resources:
  homepage: http://search.cpan.org/dist/DBD-ODBC/
  license: http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DBD-ODBC
  MailingList: http://dbi.perl.org/support
  repository: http://svn.perl.org/modules/dbd-odbc
installdirs:  site
keywords:
  - ODBC
  - DBD
  - DBI
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Martin J. Evans
# ensure there is a newline at the end of this file or pause objects
